# ------------------------------------
#   欢迎您使用阿里云函数计算 FC 组件进行项目开发
#   组件仓库地址/帮助文档：https://github.com/devsapp/fc
#   Yaml参考文档：https://github.com/devsapp/fc/blob/main/docs/zh/yaml.md
#   快速入门：
#      快速创建应用：https://github.com/devsapp/fc/blob/main/docs/zh/quick_start_application.md
#      快速使用命令：https://github.com/devsapp/fc/blob/main/docs/zh/quick_start_function.md
# ------------------------------------

edition: 1.0.0
name: helloworldApp
access: "{{ access }}"
vars:
  region: cn-hangzhou
services:
  helloworld:
    component: fc
    actions: # 自定义执行逻辑
      pre-deploy: # 在deploy之前运行
        - run: s build --use-docker --dockerfile ./code/Dockerfile  # 要运行的命令行
          path: ./ # 命令行运行的路径
    props:
      region: ${vars.region}
      service:
        name: hello-world-service
      function:
        name: cpp-http-function
        description: 'hello world by serverless devs'
        caPort: 9000
        memorySize: 256
        handler: not-used
        timeout: 60
        initializationTimeout: 30
        initializer: not-used
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-hangzhou.aliyuncs.com/fc-demo/fc-springboot-http:v0.1 # 需要换成自己的registry地址
        codeUri: ./code
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
              methods:
                - GET
                - POST
